### ISSUE TITLE
LaTex installation required

### ISSUE THREAD

**Issue by gregordecristoforo** [uit-cosmo/cosmoplots#33]
Maybe mention in the README that LaTex needs to be installed on your system. Otherwise, you get the following:

```Python
RuntimeError: Failed to process string with tex because latex could not be found
```

**Comment by engeir** [comment]
In an [empty ubuntu image](https://github.com/bast/teaching-setup) and with an installation of [tinytex](https://yihui.org/tinytex/), the following packages was also needed:

```bash
tlmgr install cm-super
tlmgr install type1cm
tlmgr install underscore
tlmgr install dvipng
```

Maybe that's fine to specify, although I guess latex is kind of tricky with all the distributions out there, so maybe being less specific and just saying latex is needed would actually be better.
